CONFIG_ZMK_SLEEP=y

# 蓝牙增强
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

CONFIG_ZMK_KEYBOARD_NAME="Aurora"
CONFIG_BT_DEVICE_NAME="Aurora-BT"